import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Calendar, User, ArrowRight, BookOpen, Plus } from "lucide-react";
import { format } from "date-fns";
import BlogSubmissionForm from "@/components/blog-submission-form";
export default function BlogPage() {
    const [activeTab, setActiveTab] = useState("posts");
    const { data: blogResponse, isLoading } = useQuery({
        queryKey: ["/api/blog"],
    });
    const blogPosts = (blogResponse === null || blogResponse === void 0 ? void 0 : blogResponse.data) || [];
    if (isLoading) {
        return (_jsx("div", { className: "min-h-screen bg-gray-50 py-12", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "animate-spin rounded-full h-32 w-32 border-b-2 border-primary mx-auto" }), _jsx("p", { className: "mt-4 text-gray-600", children: "Loading blog posts..." })] }) }) }));
    }
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("section", { className: "bg-gradient-to-r from-primary to-blue-700 text-white py-20", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center", children: [_jsx(BookOpen, { className: "w-16 h-16 mx-auto mb-6" }), _jsx("h1", { className: "text-4xl md:text-5xl font-bold mb-4", children: "UBa Tech Camp Blog" }), _jsx("p", { className: "text-xl text-blue-100 max-w-2xl mx-auto", children: "Insights, stories, and updates from our tech education community" })] }) }), _jsx("section", { className: "py-16", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs(Tabs, { value: activeTab, onValueChange: setActiveTab, className: "w-full", children: [_jsxs(TabsList, { className: "grid w-full grid-cols-2 max-w-md mx-auto mb-8", children: [_jsxs(TabsTrigger, { value: "posts", className: "flex items-center gap-2", children: [_jsx(BookOpen, { className: "w-4 h-4" }), "Blog Posts"] }), _jsxs(TabsTrigger, { value: "submit", className: "flex items-center gap-2", children: [_jsx(Plus, { className: "w-4 h-4" }), "Write a Post"] })] }), _jsx(TabsContent, { value: "posts", className: "mt-0", children: blogPosts.length === 0 ? (_jsxs("div", { className: "text-center py-12", children: [_jsx(BookOpen, { className: "w-24 h-24 text-gray-300 mx-auto mb-4" }), _jsx("h3", { className: "text-2xl font-semibold text-gray-900 mb-2", children: "No Blog Posts Yet" }), _jsx("p", { className: "text-gray-600 max-w-md mx-auto", children: "We're working on creating amazing content for you. Check back soon for insights and stories from our tech community!" })] })) : (_jsx("div", { className: "grid md:grid-cols-2 lg:grid-cols-3 gap-8", children: blogPosts.map((post) => (_jsxs(Card, { className: "hover:shadow-lg transition-shadow duration-300 overflow-hidden", children: [post.featuredImage && (_jsx("div", { className: "h-48 bg-gray-200 overflow-hidden", children: _jsx("img", { src: post.featuredImage, alt: post.title, className: "w-full h-full object-cover" }) })), _jsxs(CardHeader, { className: "pb-3", children: [post.category && (_jsx(Badge, { variant: "secondary", className: "w-fit mb-2", children: post.category })), _jsx("h2", { className: "text-xl font-bold text-gray-900 mb-2 line-clamp-2", children: post.title }), post.excerpt && (_jsx("p", { className: "text-gray-600 text-sm line-clamp-3", children: post.excerpt }))] }), _jsxs(CardContent, { className: "pt-0", children: [_jsxs("div", { className: "flex items-center text-sm text-gray-500 mb-4", children: [_jsx(User, { className: "w-4 h-4 mr-1" }), _jsx("span", { className: "mr-4", children: post.authorName }), _jsx(Calendar, { className: "w-4 h-4 mr-1" }), _jsx("span", { children: post.publishedAt
                                                                    ? format(new Date(post.publishedAt), 'MMM dd, yyyy')
                                                                    : format(new Date(post.createdAt), 'MMM dd, yyyy') })] }), post.tags && post.tags.length > 0 && (_jsx("div", { className: "flex flex-wrap gap-1 mb-4", children: post.tags.map((tag) => (_jsx(Badge, { variant: "outline", className: "text-xs", children: tag }, tag))) })), _jsx(Link, { href: `/blog/${post.slug}`, children: _jsxs(Button, { variant: "outline", className: "w-full group", children: ["Read More", _jsx(ArrowRight, { className: "w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" })] }) })] })] }, post.id))) })) }), _jsx(TabsContent, { value: "submit", className: "mt-0", children: _jsx(BlogSubmissionForm, {}) })] }) }) })] }));
}
