import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Facebook, Twitter, Linkedin, Instagram } from "lucide-react";
import logoImage from "@assets/new logo.jpg";
export default function Footer() {
    const scrollToSection = (sectionId) => {
        const element = document.getElementById(sectionId);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth' });
        }
    };
    return (_jsx("footer", { className: "bg-gray-900 text-white py-12", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "grid md:grid-cols-4 gap-8", children: [_jsxs("div", { className: "col-span-2", children: [_jsxs("div", { className: "flex items-center space-x-3 mb-4", children: [_jsx("img", { src: logoImage, alt: "UBa Tech Camp Logo", className: "h-12 w-12 object-contain rounded-full" }), _jsx("h3", { className: "text-2xl font-bold", children: "UBa Tech Camp" })] }), _jsx("p", { className: "text-gray-400 mb-4", children: "Empowering youth with digital skills through comprehensive, hands-on training programs." }), _jsxs("div", { className: "flex space-x-4", children: [_jsx("a", { href: "#", className: "text-gray-400 hover:text-white transition-colors", children: _jsx(Facebook, { className: "h-5 w-5" }) }), _jsx("a", { href: "#", className: "text-gray-400 hover:text-white transition-colors", children: _jsx(Twitter, { className: "h-5 w-5" }) }), _jsx("a", { href: "#", className: "text-gray-400 hover:text-white transition-colors", children: _jsx(Linkedin, { className: "h-5 w-5" }) }), _jsx("a", { href: "#", className: "text-gray-400 hover:text-white transition-colors", children: _jsx(Instagram, { className: "h-5 w-5" }) })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-lg font-semibold mb-4", children: "Quick Links" }), _jsxs("ul", { className: "space-y-2 text-gray-400", children: [_jsx("li", { children: _jsx("button", { onClick: () => scrollToSection('learn'), className: "hover:text-white transition-colors", children: "What You'll Learn" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection('team'), className: "hover:text-white transition-colors", children: "Our Team" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection('projects'), className: "hover:text-white transition-colors", children: "Projects" }) }), _jsx("li", { children: _jsx("button", { onClick: () => scrollToSection('register'), className: "hover:text-white transition-colors", children: "Register" }) })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-lg font-semibold mb-4", children: "Contact Info" }), _jsxs("ul", { className: "space-y-2 text-gray-400", children: [_jsx("li", { children: "University of Bamenda" }), _jsx("li", { children: "info.ubatechcamp@gmail.com" }), _jsx("li", { children: "+237 671 308 991" })] })] })] }), _jsx("div", { className: "border-t border-gray-800 mt-8 pt-8 text-center text-gray-400", children: _jsx("p", { children: "\u00A9 2025 UBa Tech Camp. All rights reserved. | In partnership with University of Bamenda" }) })] }) }));
}
